#include "citrus/move/MoveGenerator.h"

/**
 * \brief The system responsible for finding good moves to play.
 * 
 * This is the "brain" of the program; the core of the decision-making process.
 * It looks ahead at the different paths a game can take and determines the
 * one with the highest chance of winning.
 */
class Searcher {
	public:
		/**
		 * \brief The information given by a search.
		 * 
		 * The score and chosen move are needed to find the best move.
		 * The rest are there to provide information about the search node.
		 */
		struct SearchResult {
			int score;
			Move chosen_move;
			uint64_t node;
		};
		
		/**
		 * \brief Gets the current depth of the Searcher.
		 * 
		 * \return the depth.
		 */
		int get_depth();
		
		/**
		 * \brief Sets a new depth for the Searcher.
		 * 
		 * \param the depth.
		 */
		
		void set_depth(int depth);
		
		/**
		 * \brief Finds the ideal move that can be made from a given position.
		 * 
		 * It is a depth-first negamax search. The larger the depth, the more informed
		 * the search will be. However, this will also exponentially increase the time it
		 * takes to arrive at an answer.
		 * 
		 * The following optimizations are in use:
		 * - Alpha-beta pruning
		 * 
		 * \param pos the current position of the game.
		 * \return the best move that can be made.
		 */
		Move find_best_move(Position &pos);
	private:
		/// \brief The maximum search depth.
		constexpr static int MAX_SEARCH_PLY = 128;
		
		/// \brief Arbitrarily high integer.
		constexpr static int INF = 9999999;
		
		/// \brief Pre-allocated MoveLists indexed by depth.
		std::array<MoveList, MAX_SEARCH_PLY> list_stack;
		
		/// \brief Generates moves for the search.
		MoveGenerator move_generator;
		
		/// \brief The search depth.
		int depth = 5;
		
		/// \brief The number of nodes generated by the current/last search.
		uint64_t node_count = 0;
			
		/**
		 * \brief Recursive search to find the highest-value move from a position.
		 * 
		 * \param pos the position that moves will be derived from.
		 * \param depth the current depth of the search
		 * \param alpha minimum assured score of maximizing side
		 * \param beta maximum assured score of minimizing side
		 * \return the best move (and related info) from the position.
		 */
		SearchResult negamax(Position &pos, int depth, int alpha, int beta);
};
