#include "citrus/move/MoveGenerator.h"
#include <chrono>
#include <atomic>

/**
 * \brief The system responsible for finding good moves to play.
 * 
 * This is the "brain" of the program; the core of the decision-making process.
 * It looks ahead at the different paths a game can take and determines the
 * one with the highest chance of winning.
 */
class Searcher {
	public:
		/**
		 * \brief The information given by a search.
		 * 
		 * The score and chosen move are needed to find the best move.
		 * The rest are there to provide information about the search node.
		 */
		struct SearchResult {
			int score;
			Move chosen_move;
			uint64_t node;
		};
		
		/**
		 * \brief Options that determine the type of search to be conducted.
		 * 
		 * All time is measured in milliseconds.
		 * 
		 * - depth: local maximum search depth
		 * - wtime / btime: time remaining for either side
		 * - winc / binc: time taken to make latest move
		 * - movestogo: halfmoves until next time control
		 * - max_nodes: maximum nodes to be searched
		 * - movetime: maximum time to search
		 * - finite_nodes: indicates that search must be stopped once max_nodes is reached
		 * - finite_time: indicates that search must be stopped once movetime is reached
		 * 
		 * Several of these currently do nothing.
		 */
		struct SearchSettings {
			int depth = 5;
			int wtime = 0;
			int btime = 0;
			int winc = 0;
			int binc = 0;
			int movestogo = 0;
			int max_nodes = 0;
			int movetime = 0;
			bool finite_nodes = false;
			bool finite_time = false;
		};
		
		/// \brief The maximum search depth.
		constexpr static int MAX_SEARCH_PLY = 128;
		
		/// \brief Local settings for current search.
		SearchSettings settings;
		
		/// \brief Reference to search stopping flag.
		std::atomic<bool> &stopping;
		
		/// \brief Point in time where the search started.
		std::chrono::steady_clock::time_point start_time;
		
		/**
		 * \brief Constructs a searcher.
		 * 
		 * \param stopper reference to the search stopping flag.
		 */
		Searcher(std::atomic<bool> &stopper) : stopping(stopper) {}
		
		/**
		 * \brief Determines whether a evaluation score indicates checkmate.
		 * 
		 * \param score the score to be examined.
		 * \return whether the score indicates checkmate.
		 */
		bool is_mate_score(int score);
		
		/**
		 * \brief Determines whether the movetime has been reached.
		 * 
		 * Getting the current time is not computationally free, so this should not be run every node.
		 * 
		 * \return whether movetime has been reached.
		 */
		bool time_limit_reached();
		
		/**
		 * \brief Finds the ideal move that can be made from a given position.
		 * 
		 * It is a depth-first negamax search. The larger the depth, the more informed
		 * the search will be. However, this will also exponentially increase the time it
		 * takes to arrive at an answer.
		 * 
		 * The following optimizations are in use:
		 * - Alpha-beta pruning
		 * 
		 * \param pos the current position of the game.
		 * \return the best move that can be made.
		 */
		Move find_best_move(Position pos);
		
		//Move find_mate(Position &pos, int depth);
	private:
		/// \brief Arbitrarily high integer.
		constexpr static int INF = 9999999;
		
		/// \brief Value of a position in checkmate.
		constexpr static int MATE = 5000000;
		
		/// \brief Pre-allocated MoveLists indexed by depth.
		std::array<MoveList, MAX_SEARCH_PLY> list_stack;
		
		/// \brief Generates moves for the search.
		MoveGenerator move_generator;
		
		/// \brief The number of nodes generated by the current/last search.
		uint64_t node_count = 0;
			
		/**
		 * \brief Recursive search to find the highest-value move from a position.
		 * 
		 * Results are dependent on the current search settings.
		 * 
		 * \param pos the position that moves will be derived from.
		 * \param depth the current depth of the search
		 * \param alpha minimum assured score of maximizing side
		 * \param beta maximum assured score of minimizing side
		 * \return the best move (and related info) from the position.
		 */
		SearchResult negamax(Position &pos, int depth, int alpha, int beta);
};
